name: fooodify
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  cloud_firestore: ^2.3.0
  razorpay_flutter: ^1.2.6
  toast: ^0.1.5
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/baseline_home_black_24dp.png
    - images/baseline_search_black_24dp.png
    - images/outline_bookmark_black_24dp.png

  fonts:
    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf
    - family: MontBold
      fonts:
        - asset: fonts/Montserrat-ExtraBold.ttf
    - family: MontSerrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

